### ISSUE TITLE
Pencarian LBC tidak berfungsi

### ISSUE THREAD

**Issue by awriel** [drajathasan/label_barcode_color_slims#1]
Bro, baris 200 pada berkas **label_barcode_warna_generator.php** sepertinya masih ada yang kurang. 

Berkas di github:
 ` <form name="search" action="<?php echo MWB; ?>bibliography/label_barcode_warna_generator.php" id="search" method="get" class="form-inline"><?php echo __('Search'); ?> `

bukankah seharusnya : 

 ` <form name="search" action="<?php echo MWB; ?>bibliography/lbc/label_barcode_warna_generator.php" id="search" method="get" class="form-inline"><?php echo __('Search'); ?> `

Terima kasih.

**Comment by drajathasan** [comment]
Ok siap mas. Terimakasih sudah report. Segera tak edit.
